language: node_js
node_js:
- 8
before_deploy:
- npm run build
deploy:
  provider: npm
  email: karim@alibhai.co
  api_key:
    secure: ekp3YGbCJHbJh8czfjkg24dIlnNTUhUewsNLdgtK7Uzsvp6YKj3vlKoBxjw0kJs2j0XLDRLsDSDL5PdHSje669w1Vsh/XU3zgJ28kQnsLZvhlRgkTq1Q0UX2T/Xq6RUvUpLIPRLNRM44TWpmOLRix0jyMrmriedbO8RLzQGVPHjI1pAa/cdIw5jFfT2h6+8rwxAJbwexM8h6Rf9VcxFa2wUi55GhzITKIQFyBwOYutuL4/J+m8F8Pbl3fDiP/MsL/Iyr3bjPGeHFkuDe+moQ+1BRPSndyVqGA+jwd+S5VovIPrkZXbdHk/tdgdAPosYZNzX31JVLBqN3S9jSNxqrm1XOukQBSSa6qGLU6a6xnBTnbyjL+Mn5Nsri/qoir2EvsW91uB9VMPrhY788VqyTHX4EBtpudDbTizCnZ0bT4T9cm91COtdQSNcU+QILoWaK54Mn3UGT5gkmwIMAOJf1uTIaVMQzLvyYz6KIS5kc99ecm7INYcfNGGt1JBWaymLD7xS/gDn9C+2RFw14+aLwSUDTTpJ+8Jl2s3yTVaznESpxNGrp1pAPRQqr91uaWcahTCpwzmdhIQzZcW/haiAnj5xPZ4/L8cGzCxIwICGlM16thk8Bt+3fEuSGnzO1RtC8Aj6z3hdAFEauHzYgzEFy/gRyaePSNg+E+szCfnVJLn8=
  on:
    tags: true
    repo: karimsa/tardis
